controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    l_leg_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_speed_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_pid_controller:
      type: pid_command_controller/PIDCommandController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false

l_leg_forward_position_controller:
  ros__parameters:
    joints:
      - l_leg_pitch
    interface_name: position
    use_sim_time: false

forward_torque_controller:
  ros__parameters:
    joints:
      - l_leg_pitch
      - r_leg_pitch
    interface_name: torque
    use_sim_time: false

forward_torque_limit_controller:
  ros__parameters:
    joints:
      - l_leg_pitch
      - r_leg_pitch
    interface_name: torque_limit
    use_sim_time: false

forward_speed_limit_controller:
  ros__parameters:
    joints:
      - l_leg_pitch
      - r_leg_pitch
    interface_name: speed_limit
    use_sim_time: false


forward_pid_controller:
  ros__parameters:
    joints:
      - l_leg_pitch
      - r_leg_pitch
    use_sim_time: false
