controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    l_leg_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    r_leg_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_speed_limit_controller:
      type: forward_command_controller/ForwardCommandController

    forward_pid_controller:
      type: pid_command_controller/PIDCommandController

l_leg_forward_position_controller:
  ros__parameters:
    joints:
      - hip_hinge_joint.L
      - leg_joint.L
      - thigh_joint.L
      - foot_joint.L
    interface_name: position
    
r_leg_forward_position_controller:
  ros__parameters:
    joints:
      - hip_hinge_joint.R
      - leg_joint.R
      - thigh_joint.R
      - foot_joint.R
    interface_name: position

forward_torque_controller:
  ros__parameters:
    joints:
      - spine_joint
      - hip_hinge_joint.L
      - hip_hinge_joint.R
      - leg_joint.L
      - leg_joint.R
      - thigh_joint.L
      - thigh_joint.R
      - foot_joint.L
      - foot_joint.R
    interface_name: torque
    
forward_torque_limit_controller:
  ros__parameters:
    joints:
      - spine_joint
      - hip_hinge_joint.L
      - hip_hinge_joint.R
      - leg_joint.L
      - leg_joint.R
      - thigh_joint.L
      - thigh_joint.R
      - foot_joint.L
      - foot_joint.R
    interface_name: torque_limit
    
forward_speed_limit_controller:
  ros__parameters:
    joints:
      - spine_joint
      - hip_hinge_joint.L
      - hip_hinge_joint.R
      - leg_joint.L
      - leg_joint.R
      - thigh_joint.L
      - thigh_joint.R
      - foot_joint.L
      - foot_joint.R
    interface_name: speed_limit

forward_pid_controller:
  ros__parameters:
    joints:
      - spine_joint
      - hip_hinge_joint.L
      - hip_hinge_joint.R
      - leg_joint.L
      - leg_joint.R
      - thigh_joint.L
      - thigh_joint.R
      - foot_joint.L
      - foot_joint.R
